### ISSUE TITLE
To-Do

### ISSUE THREAD

**Issue by spencergoff** [spencergoff/MatchingNetworks#1]
- [x] Train/Test model locally using Omniglot dataset
- [x] Test model locally using Toys photos (http://www.vision.caltech.edu/pmoreels/Datasets/Giuseppe_Toys_03/)
- [ ] Locally send in a new image and get the correct classification
- [ ] Export trained model to Amazon Sagemaker (or re-train if necessary/easier)
- [ ] Make endpoint (publicly?) available
- [ ] Send image to endpoint to categorize as an existing class
- [ ] Send image to endpoint to use as a new class
- [ ] Send image to endpoint to categorize as belonging to an added class
- [ ] Divide added classes by user
- [ ] Ensure the image search only returns a class that is in that user’s directory
- [ ] Ensure user images are the same size (training images were 100x100 pixels)
